apiVersion: v1
kind: Secret
metadata:
  name: data-pipeline-secret

type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: liveklass
  DB_USER: liveklass
  DB_PASSWORD: liveklass1111
